//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrictionlessRefueling.Biz.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEntry
    {
        public int Id { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<float> FuelRead { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
